# src/main/resources/application.yml
server:
  port: $PORT
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: BjG8ksiKXDkX9BCHjECsyu72vvUw76Sv
            client-secret: WNH6RdStWkNgrNpL9otLt2OQ4VMy5vz3YFPrbFoRPy3jWWbRfLV3eekwy2-5COxc
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://erossiano.us.auth0.com/